# Generated by Django 3.2.7 on 2021-09-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20210911_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=43534),
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.IntegerField(default=9957587367),
        ),
        migrations.AddField(
            model_name='user',
            name='email_id',
            field=models.EmailField(default='user@gmail.com', max_length=254),
        ),
    ]
