# Generated by Django 3.2.7 on 2021-09-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20210911_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('amount', models.IntegerField(verbose_name='Rs')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(verbose_name='Rs'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
