# Generated by Django 3.2.7 on 2021-09-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20210912_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.IntegerField(verbose_name='Amount (₹)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(verbose_name='Balance (₹)'),
        ),
    ]
